### ISSUE TITLE
App configuration is stored in user's home directory, not somewhere user agnostic

### ISSUE THREAD

**Issue by manofcolombia** [CiscoDevNet/csdac-ansible#6]
```
- name: "Find current user"
  set_fact:
    current_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

- name: Find user home directory
  shell: >
    getent passwd {{ ansible_env.SUDO_USER | default(ansible_user_id) }} | cut -d: -f6
  changed_when: false
  register: home_directory

- name: Variable for CSDAC directory
  set_fact:
    CSDAC_DIR: "{{ home_directory.stdout }}/csdac/app"

- name: Create directory structure in csdac vm
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
  with_items:
    - "{{ CSDAC_DIR }}/config/connectors"
    - "{{ CSDAC_DIR }}/config/adapters"
    - "{{ CSDAC_DIR }}/config/certs"
```

The snippet above forces the configuration for the app to be stored in the user's that executing the playbook home directory. This can be a problem if that user account is not a local account or service account. 

**Example:** 
If user leaves the company and permissions are cleaned up, including any home directories across servers, this application would break

**Solution:** 
Either pick another location that is more user agnostic to store app config or allow the user to specify location for app config as a playbook arg.
